services:
  backend:
    build:
      context: ./repository-secret-service
    ports:
      - "8081:8081"
    networks:
      - cicd-network

  frontend:
    build:
      context: ./repository-secret-ui
    ports:
      - "8080:8080"
    environment:
    - HOST=0.0.0.0
    depends_on:
      - backend
    networks:
      - cicd-network

networks:
  cicd-network:
    driver: bridge