spring.application.name=repository-secret-service

# Start the server on port 8080 (default)
server.port=8081

# H2 Database Settings (In-memory)
spring.datasource.url=jdbc:h2:mem:cicddb
spring.datasource.driverClassName=org.h2.Driver
# Using placeholders. The syntax is ${VARIABLE_NAME:default_value}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

# Allows automatic creation of tables based on your Entity classes
spring.jpa.hibernate.ddl-auto=update

# Enable the H2 Console (To view tables via your browser!)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# (Optional, but useful) Shows SQL queries in the console when the application is running
spring.jpa.show-sql=true

# global prefix for all REST endpoints
server.servlet.context-path=/api/v1